/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RadarIndexRouteImport } from './routes/radar.index'
import { Route as RadarAgendaRouteImport } from './routes/radar.agenda'
import { Route as RadarAlunosRouteImport } from './routes/radar.alunos'
import { Route as RadarConfigRouteImport } from './routes/radar.config'
import { Route as RadarIndicadoresRouteImport } from './routes/radar.indicadores'
import { Route as RadarPedagogicoRouteImport } from './routes/radar.pedagogico'
import { Route as TutorIndexRouteImport } from './routes/tutor.index'
import { Route as TutorDesempenhoRouteImport } from './routes/tutor.desempenho'
import { Route as TutorMetaRouteImport } from './routes/tutor.meta'
import { Route as TutorPlanoRouteImport } from './routes/tutor.plano'
import { Route as TutorProvasRouteImport } from './routes/tutor.provas'
import { Route as RadarAlunoIdRouteImport } from './routes/radar.aluno.$id'
import { Route as RadarAlunoIdHistoricoRouteImport } from './routes/radar.aluno.$id.historico'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarIndexRoute = RadarIndexRouteImport.update({
  id: '/radar/',
  path: '/radar/',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarAgendaRoute = RadarAgendaRouteImport.update({
  id: '/radar/agenda',
  path: '/radar/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarAlunosRoute = RadarAlunosRouteImport.update({
  id: '/radar/alunos',
  path: '/radar/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarConfigRoute = RadarConfigRouteImport.update({
  id: '/radar/config',
  path: '/radar/config',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarIndicadoresRoute = RadarIndicadoresRouteImport.update({
  id: '/radar/indicadores',
  path: '/radar/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarPedagogicoRoute = RadarPedagogicoRouteImport.update({
  id: '/radar/pedagogico',
  path: '/radar/pedagogico',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorIndexRoute = TutorIndexRouteImport.update({
  id: '/tutor/',
  path: '/tutor/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorDesempenhoRoute = TutorDesempenhoRouteImport.update({
  id: '/tutor/desempenho',
  path: '/tutor/desempenho',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorMetaRoute = TutorMetaRouteImport.update({
  id: '/tutor/meta',
  path: '/tutor/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorPlanoRoute = TutorPlanoRouteImport.update({
  id: '/tutor/plano',
  path: '/tutor/plano',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorProvasRoute = TutorProvasRouteImport.update({
  id: '/tutor/provas',
  path: '/tutor/provas',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarAlunoIdRoute = RadarAlunoIdRouteImport.update({
  id: '/radar/aluno/$id',
  path: '/radar/aluno/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarAlunoIdHistoricoRoute = RadarAlunoIdHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => RadarAlunoIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/radar/agenda': typeof RadarAgendaRoute
  '/radar/alunos': typeof RadarAlunosRoute
  '/radar/config': typeof RadarConfigRoute
  '/radar/indicadores': typeof RadarIndicadoresRoute
  '/radar/pedagogico': typeof RadarPedagogicoRoute
  '/tutor/desempenho': typeof TutorDesempenhoRoute
  '/tutor/meta': typeof TutorMetaRoute
  '/tutor/plano': typeof TutorPlanoRoute
  '/tutor/provas': typeof TutorProvasRoute
  '/radar/': typeof RadarIndexRoute
  '/tutor/': typeof TutorIndexRoute
  '/radar/aluno/$id': typeof RadarAlunoIdRouteWithChildren
  '/radar/aluno/$id/historico': typeof RadarAlunoIdHistoricoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/radar/agenda': typeof RadarAgendaRoute
  '/radar/alunos': typeof RadarAlunosRoute
  '/radar/config': typeof RadarConfigRoute
  '/radar/indicadores': typeof RadarIndicadoresRoute
  '/radar/pedagogico': typeof RadarPedagogicoRoute
  '/tutor/desempenho': typeof TutorDesempenhoRoute
  '/tutor/meta': typeof TutorMetaRoute
  '/tutor/plano': typeof TutorPlanoRoute
  '/tutor/provas': typeof TutorProvasRoute
  '/radar': typeof RadarIndexRoute
  '/tutor': typeof TutorIndexRoute
  '/radar/aluno/$id': typeof RadarAlunoIdRouteWithChildren
  '/radar/aluno/$id/historico': typeof RadarAlunoIdHistoricoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/radar/agenda': typeof RadarAgendaRoute
  '/radar/alunos': typeof RadarAlunosRoute
  '/radar/config': typeof RadarConfigRoute
  '/radar/indicadores': typeof RadarIndicadoresRoute
  '/radar/pedagogico': typeof RadarPedagogicoRoute
  '/tutor/desempenho': typeof TutorDesempenhoRoute
  '/tutor/meta': typeof TutorMetaRoute
  '/tutor/plano': typeof TutorPlanoRoute
  '/tutor/provas': typeof TutorProvasRoute
  '/radar/': typeof RadarIndexRoute
  '/tutor/': typeof TutorIndexRoute
  '/radar/aluno/$id': typeof RadarAlunoIdRouteWithChildren
  '/radar/aluno/$id/historico': typeof RadarAlunoIdHistoricoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/radar/agenda'
    | '/radar/alunos'
    | '/radar/config'
    | '/radar/indicadores'
    | '/radar/pedagogico'
    | '/tutor/desempenho'
    | '/tutor/meta'
    | '/tutor/plano'
    | '/tutor/provas'
    | '/radar/'
    | '/tutor/'
    | '/radar/aluno/$id'
    | '/radar/aluno/$id/historico'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/radar/agenda'
    | '/radar/alunos'
    | '/radar/config'
    | '/radar/indicadores'
    | '/radar/pedagogico'
    | '/tutor/desempenho'
    | '/tutor/meta'
    | '/tutor/plano'
    | '/tutor/provas'
    | '/radar'
    | '/tutor'
    | '/radar/aluno/$id'
    | '/radar/aluno/$id/historico'
  id:
    | '__root__'
    | '/'
    | '/radar/agenda'
    | '/radar/alunos'
    | '/radar/config'
    | '/radar/indicadores'
    | '/radar/pedagogico'
    | '/tutor/desempenho'
    | '/tutor/meta'
    | '/tutor/plano'
    | '/tutor/provas'
    | '/radar/'
    | '/tutor/'
    | '/radar/aluno/$id'
    | '/radar/aluno/$id/historico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RadarAgendaRoute: typeof RadarAgendaRoute
  RadarAlunosRoute: typeof RadarAlunosRoute
  RadarConfigRoute: typeof RadarConfigRoute
  RadarIndicadoresRoute: typeof RadarIndicadoresRoute
  RadarPedagogicoRoute: typeof RadarPedagogicoRoute
  TutorDesempenhoRoute: typeof TutorDesempenhoRoute
  TutorMetaRoute: typeof TutorMetaRoute
  TutorPlanoRoute: typeof TutorPlanoRoute
  TutorProvasRoute: typeof TutorProvasRoute
  RadarIndexRoute: typeof RadarIndexRoute
  TutorIndexRoute: typeof TutorIndexRoute
  RadarAlunoIdRoute: typeof RadarAlunoIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar/': {
      id: '/radar/'
      path: '/radar'
      fullPath: '/radar/'
      preLoaderRoute: typeof RadarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar/agenda': {
      id: '/radar/agenda'
      path: '/radar/agenda'
      fullPath: '/radar/agenda'
      preLoaderRoute: typeof RadarAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar/alunos': {
      id: '/radar/alunos'
      path: '/radar/alunos'
      fullPath: '/radar/alunos'
      preLoaderRoute: typeof RadarAlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar/config': {
      id: '/radar/config'
      path: '/radar/config'
      fullPath: '/radar/config'
      preLoaderRoute: typeof RadarConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar/indicadores': {
      id: '/radar/indicadores'
      path: '/radar/indicadores'
      fullPath: '/radar/indicadores'
      preLoaderRoute: typeof RadarIndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar/pedagogico': {
      id: '/radar/pedagogico'
      path: '/radar/pedagogico'
      fullPath: '/radar/pedagogico'
      preLoaderRoute: typeof RadarPedagogicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/': {
      id: '/tutor/'
      path: '/tutor'
      fullPath: '/tutor/'
      preLoaderRoute: typeof TutorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/desempenho': {
      id: '/tutor/desempenho'
      path: '/tutor/desempenho'
      fullPath: '/tutor/desempenho'
      preLoaderRoute: typeof TutorDesempenhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/meta': {
      id: '/tutor/meta'
      path: '/tutor/meta'
      fullPath: '/tutor/meta'
      preLoaderRoute: typeof TutorMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/plano': {
      id: '/tutor/plano'
      path: '/tutor/plano'
      fullPath: '/tutor/plano'
      preLoaderRoute: typeof TutorPlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/provas': {
      id: '/tutor/provas'
      path: '/tutor/provas'
      fullPath: '/tutor/provas'
      preLoaderRoute: typeof TutorProvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar/aluno/$id': {
      id: '/radar/aluno/$id'
      path: '/radar/aluno/$id'
      fullPath: '/radar/aluno/$id'
      preLoaderRoute: typeof RadarAlunoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar/aluno/$id/historico': {
      id: '/radar/aluno/$id/historico'
      path: '/historico'
      fullPath: '/radar/aluno/$id/historico'
      preLoaderRoute: typeof RadarAlunoIdHistoricoRouteImport
      parentRoute: typeof RadarAlunoIdRoute
    }
  }
}

interface RadarAlunoIdRouteChildren {
  RadarAlunoIdHistoricoRoute: typeof RadarAlunoIdHistoricoRoute
}

const RadarAlunoIdRouteChildren: RadarAlunoIdRouteChildren = {
  RadarAlunoIdHistoricoRoute: RadarAlunoIdHistoricoRoute,
}

const RadarAlunoIdRouteWithChildren = RadarAlunoIdRoute._addFileChildren(
  RadarAlunoIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RadarAgendaRoute: RadarAgendaRoute,
  RadarAlunosRoute: RadarAlunosRoute,
  RadarConfigRoute: RadarConfigRoute,
  RadarIndicadoresRoute: RadarIndicadoresRoute,
  RadarPedagogicoRoute: RadarPedagogicoRoute,
  TutorDesempenhoRoute: TutorDesempenhoRoute,
  TutorMetaRoute: TutorMetaRoute,
  TutorPlanoRoute: TutorPlanoRoute,
  TutorProvasRoute: TutorProvasRoute,
  RadarIndexRoute: RadarIndexRoute,
  TutorIndexRoute: TutorIndexRoute,
  RadarAlunoIdRoute: RadarAlunoIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
